#!/usr/bin/env bash

for i in $(cat ~/.ssh/config | grep Host | grep HostName | awk '{ print $2 }'); do
    ssh-keygen -f "/root/.ssh/known_hosts" -R $i
    ssh-copy-id -i ~/.ssh/id_rsa.pub root@"$i"
done

# Test connectivity
for i in $(cat ~/.ssh/config | grep Host | grep -v HostName | awk '{ print $2 }'); do
    echo "Test ssh to $i"; ssh $i "exit"; 
done
