#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Illegal number of args"
    exit
fi

if [ $1 = "swift" ]; then
    umount /disk0; swapoff -a; rm -rf /srv/node/*;
    DRIVECOUNT=0
    for m in $(lsblk -o MOUNTPOINT | grep -v MOUNTPOINT | grep -v ^$ | grep osd); do
        umount -f $m
        DRIVECOUNT+=1
    done
    # TODO: test fstab edit
    head -n -$DRIVECOUNT /etc/fstab > /etc/fstab
elif [ $1 = "ceph" ]; then
    rm -rf /etc/ceph; rm -rf /var/lib/ceph ; rm -rf /var/run/ceph
    DRIVECOUNT=0
    for m in $(lsblk -o MOUNTPOINT | grep -v MOUNTPOINT | grep -v ^$ | grep osd); do
        umount -f $m
        DRIVECOUNT+=1
    done
    # TODO: test fstab edit
    head -n -$DRIVECOUNT /etc/fstab > /etc/fstab
else
    echo "Illegal arg value. Please supply either 'ceph' or 'swift'"
    exit
fi

for d in $(lsblk -d -o NAME | grep -v NAME); do
    sgdisk --zap /dev/"$d"
    dd if=/dev/zero of=/dev/"$d" bs=1M count=512
done
