#!/usr/bin/env bash
# Used for removing unneeded services on current controller nodes
# when migrating to enterprise

# removes MOST controller services
for f in $(cat services.txt); do
    service $f stop
    rm -f /etc/init.d/$f
    rm -f /etc/init/"$f".conf
done

# separate 2 edge cases to avoid many unneeded conditional checks
service mysql stop && service rabbitmq-server stop
sudo apt-get remove -y percona-xtradb-cluster-common-5.6 mysql-common rabbitmq-server
rm -f /etc/init.d/rabbitmq-server
