#!/usr/bin/env bash

for f in $(cat services.txt); do
    service $f stop
    mv /etc/init/"$f".conf /etc/init/"$f".conf.bak
done

# separate 2 edge cases to avoid many unneeded conditional checks
service mysql stop && service rabbitmq-server stop
sudo apt-get remove -y percona-xtradb-cluster-common-5.6 mysql-common rabbitmq-server
